lnd:
  macaroonPath: macaroons
  scraping:
    threads: 10
    timeoutSec: 10
    successMetricName: scrape_successful
  scrapers:
    channel_route_test:
      channel01:
        channelId: 1637407009740881920
        amount: 1
    channel_active:
      channel01:
        channelId: 1637407009740881920
    channel_balance_local:
      channel01:
        channelId: 1637407009740881920
    channel_balance_remote:
      channel01:
        channelId: 1637407009740881920
    channel_routing_activity:
      channel01:
        historyRangeSec: 10368000
  labels:
  - lndversion
  - exporterversion
  - pubkey
  nodes:
    fhnw-01:
      host: ip5.adrianpauli.ch
      port: 10009
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIB/DCCAaKgAwIBAgIRAIKfQYkJJDIonUB+ROQU85wwCgYIKoZIzj0EAwIwODEf
        MB0GA1UEChMWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEVMBMGA1UEAxMMMTVmZTAx
        ZmQ1MDk4MB4XDTE5MDYyNDA2NDI1NFoXDTIwMDgxODA2NDI1NFowODEfMB0GA1UE
        ChMWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEVMBMGA1UEAxMMMTVmZTAxZmQ1MDk4
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+BGIhxOPViNxUo/hqkBJRqOyLfkO
        Uw6DCnaiKRfc6B/bUqr/Eq/Ai7reDHWi6j9Vylm8ic6SbVhE7QzsqWoeXKOBjDCB
        iTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zBmBgNVHREEXzBdggwx
        NWZlMDFmZDUwOTiCCWxvY2FsaG9zdIISaXA1LmFkcmlhbnBhdWxpLmNoggR1bml4
        ggp1bml4cGFja2V0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABhwSsFAACMAoGCCqG
        SM49BAMCA0gAMEUCIDvXHJH8KRt7DcH5jve2XeH5MVUBSNJ9OP+qdchp7n1JAiEA
        xAyssKuHn8Q8WNPLedzczBKXmXnI4iEyegZtn8Q+NJM=
        -----END CERTIFICATE-----
      exporters:
        common:
        - current_block_height
        - blockchain_synced
        - channel_open
        - channel_closed
        - channel_active.channel01
        - channel_balance_local.channel01
        - channel_balance_remote.channel01
        - connected_peers
        - balance_onchain
        - balance_offchain
        - channel_routing_activity.channel01
        testpayments:
        - channel_route_test.channel01
    fhnw-02:
      host: ip5.adrianpauli.ch
      port: 10010
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIB/DCCAaKgAwIBAgIRAKiL2D9yLpVIT/th9Uj7RuUwCgYIKoZIzj0EAwIwODEf
        MB0GA1UEChMWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEVMBMGA1UEAxMMZTVkN2Mx
        NmUxZDJmMB4XDTE5MDcxNDExNDcyMFoXDTIwMDkwNzExNDcyMFowODEfMB0GA1UE
        ChMWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEVMBMGA1UEAxMMZTVkN2MxNmUxZDJm
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/yGQ7p8HhqfcidrXuAMy1Oln74pF
        /jXY/QfFWqWPFNY9lPZIPKLB8UUVL/z+fz/F+vhlurbSBq5z5oYWn7LAfaOBjDCB
        iTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zBmBgNVHREEXzBdggxl
        NWQ3YzE2ZTFkMmaCCWxvY2FsaG9zdIISaXA1LmFkcmlhbnBhdWxpLmNoggR1bml4
        ggp1bml4cGFja2V0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABhwSsFwACMAoGCCqG
        SM49BAMCA0gAMEUCIQCESI//k9SzIIOQtakkXmgNmsr6/1C5RrvK4D6ZGBeQ6gIg
        a8jaJ+GFw3zDnvv11SFWQH4DZjgIfnZeUUYJHTcXCE4=
        -----END CERTIFICATE-----
      exporters:
        common:
          - current_block_height
          - blockchain_synced
