{
 "title": "P5_IMVS15_FS19 - Template",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{node=~\".+\"}"
   },
   {
    "name": "channel_id",
    "label": "Channel Id",
    "query": "{channel_id=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    {
     "format": "short",
     "label": "0 = Not Successful, 1 = Successful"
    }
   ],
   "targets": [
    {
     "expr": "scrape_successful{node=~\"[[node]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Erreichbarkeit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_reachable{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "current_block_height{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "0 = Not Synced, 1 = Synced" }
   ],
   "targets": [
    {
     "expr": "blockchain_synced{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Channel Open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_open{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Channel Closed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_closed{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Onchain Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_onchain{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Offchain Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_offchain{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Channel Balance Local",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_balance_local{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Balance Remote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_balance_remote{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Route Test",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    {
     "format": "none",
     "label": "0 = Not Successful, 1 = Successful"
    }
   ],
   "targets": [
    {
     "expr": "channel_route_test{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "0 = Not Active. 1 = Active" }
   ],
   "targets": [
    {
     "expr": "channel_active{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Routing Activity Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_routing_activity_count{node=~\"[[node]]\"}",
     "legendFormat": "{{channel_id_in}} --> {{channel_id_out}}"
    }
   ]
  },
  {
   "title": "Routing Activity Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_routing_activity_sum{node=~\"[[node]]\"}",
     "legendFormat": "{{channel_id_in}} --> {{channel_id_out}}"
    }
   ]
  }
 ]
}