{
 "title": "P5_IMVS15_FS19 - Channels",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{node=~\".+\"}"
   },
   {
    "name": "channel_id",
    "label": "Channel Id",
    "query": "{channel_id=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_successful{node=~\"[[node]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Channel Route Test",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    {
     "format": "none",
     "label": "0 = Not Successful, 1 = Successful"
    }
   ],
   "targets": [
    {
     "expr": "channel_route_test{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "0 = Not Active. 1 = Active" }
   ],
   "targets": [
    {
     "expr": "channel_active{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Balance Local",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_balance_local{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Channel Balance Remote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_balance_remote{node=~\"[[node]]\",channel_id=~\"[[channel_id]]\"}",
     "legendFormat": "{{channel_id}}"
    }
   ]
  },
  {
   "title": "Routing Activity Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_routing_activity_count{node=~\"[[node]]\"}",
     "legendFormat": "{{channel_id_in}} --> {{channel_id_out}}"
    }
   ]
  },
  {
   "title": "Routing Activity Sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_routing_activity_sum{node=~\"[[node]]\"}",
     "legendFormat": "{{channel_id_in}} --> {{channel_id_out}}"
    }
   ]
  }
 ]
}