{
 "title": "P5_IMVS15_FS19 - Nodes",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{node=~\".+\"}"
   },
   {
    "name": "channel_id",
    "label": "Channel Id",
    "query": "{channel_id=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Scrape",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_successful{node=~\"[[node]]\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Erreichbarkeit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_reachable{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "current_block_height{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "0 = Not Synced, 1 = Synced" }
   ],
   "targets": [
    {
     "expr": "blockchain_synced{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connected_peers{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Channel Open",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_open{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Channel Closed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "channel_closed{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Onnchain Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_onchain{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Offchain Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_offchain{node=~\"[[node]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_join(node_reachable{node=~\"[[node]]\", lndversion=~\".*\"}, \"_node_\", \"\", \"node\")"
    }
   ]
  }
 ]
}